### ISSUE TITLE
Correct CSS of Logout Button in Logout.css

### ISSUE THREAD

**Issue by rnrathod16** [rnrathod16/ResumeBuilder#19]

**Comment by Abhishek07-0302** [comment]
I would like to work on this.

**Comment by rnrathod16** [comment]
@Abhishek07-0302 Make commits under master branch

**Comment by Abhishek07-0302** [comment]
I don't know why but I am unable to clone the repo . Getting clone succeded but unable to checkout error.

**Comment by rnrathod16** [comment]
@Abhishek07-0302 can you share the image of error

**Comment by rnrathod16** [comment]
@Abhishek07-0302 if you want you can edit it online with 
https://github.dev/<username>/ResumeBuilder/

just replace <username> with your Github username

**Comment by Abhishek07-0302** [comment]
Okay

**Comment by rnrathod16** [comment]
![IMG_20211003_130347](https://user-images.githubusercontent.com/71449115/135744559-28084e72-b551-47f1-935d-e2606b491479.png)

Edit file Logout.css and and work on logout button
